<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Creates new user
     *
     * @param User $user
     */
    public function add(User $user)
    {
        $this->getEntityManager()->persist($user);
    }

    /**
     * Removes user
     *
     * @param User $user
     */
    public function remove(User $user)
    {
        $this->getEntityManager()->remove($user);
    }

    /**
     * Updates user
     *
     * @param User $user
     */
    public function update(User $user)
    {
        $this->getEntityManager()->persist($user);
    }


    /**
     * Gets user by email
     *
     * @param string $email
     * @return User
     * @throws EntityNotFoundException
     */
    public function findByEmail($email)
    {
        /** @var User $user */
        $user = $this->findOneBy(['email' => $email]);

        if (!$user) {
            throw new EntityNotFoundException();
        }

        return $user;
    }

}
