# api_homepage:
#    path:     /api
#    defaults: { _controller: ApiBundle:Default:index }

tasks:
    type:     rest
    resource: ApiBundle\Controller\TasksController
    prefix:   /api

default:
    type: rest
    resource: ApiBundle\Controller\DefaultController
    prefix: /api

